version: "3.6"
services:
  app:
    #Build will look for the Dockerfile in the current directory then build the image
    build: .
    ports:
      - 3002:3002
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
